### ISSUE TITLE
No Column block exists

### ISSUE THREAD

**Issue by rospencers** [liip/bootstrap-blocks-wordpress-plugin#101]
I just did a fresh install of version 4.0.1, downloaded directly from https://wordpress.org/plugins/wp-bootstrap-blocks/

There is no Column block. 
Unfortunately, lack of a Column block makes this pretty much impossible to use.

Container, Row, and Button all exist. But no Column. If I search blocks for "bootstrap" and/or "bootstrap blocks," or if I browse all -- same result: no Column block.

This reproduces for us with multiple themes, including the WordPress core themes Twenty Twenty-Two and Twenty Twenty-One, as well as two different custom themes of our own -- all of which support Gutenberg with no difficulty.

We're running WordPress 5.9.2 with Nginx on Linux, with PHP 7.4.1. 

We also tried this on a completely different server running Apache on Linux with PHP 7.4.27. In that case, we installed directly via the Plugins admin panel. Same result: no Column block, but the other three work fine.

Below is a screenshot showing 100% of all results when searching the available blocks in the Gutenberg page editor for the phrase "bootstrap," confirming the absence of a Column block. Searching "column" also has the same result -- only the default WordPress Columns block appears.

![no-column-bootstrap-block](https://user-images.githubusercontent.com/24686373/160968606-e53326e1-5e09-46f1-9265-df2046076871.png)

**Comment by tschortsch** [comment]
Hi @rospencers. Thanks for your feedback. Actually this behavior is intended. As the column block requires to be wrapped in a row block we defined it to be only insertable in a row block. So what you need to do is inserting a row block and inside this you will be able to add as many column blocks as you would like to. Hope this helps!

**Comment by rospencers** [comment]
@tschortsch Thanks for responding, But yes, I already understand that. That's precisely the flow I am using. And that is what I am reporting: inside a Row, there no Column block provided as an option for insertion. 

Specifically:
1. I add a Container
2. Inside that I add a Row
3. In the Row is a square with a plus sign and the tooltip prompt "Add a block." 
4. I click that in order to add a Column...but there is no Column block. (Every other block in the system is available...but there is definitely no Column.)
5. If there is some other way of going about it, there is no other option, tool, prompt, or help info indicating how one is to insert or create a Column. 

Again, this behavior reproduces in more than one environment. 
Here is a screenshot showing what I've indicated with full context:

![no-Column-within-Add-Block-within-Row](https://user-images.githubusercontent.com/24686373/161109970-c01b9c16-84e0-4899-8b68-76e23d2fac2f.png)


The only things in the Row's toolbar are:
- Select Container 
- Group: Change block type or style
- Drag
- Move up/down
- Change items justification
- Change alignment
- The standard Options submenu

**Comment by tschortsch** [comment]
I just tried to reproduce your issue and I think I found the underlying problem. The "row" block you're adding inside the container is the one from the WordPress core and not the one from the plugin itself. You can differentiate them by the icons.
<img width="338" alt="row-blocks" src="https://user-images.githubusercontent.com/1061850/161123374-a1fe2a98-d2e0-48e6-acd0-d32e764189a8.png">
Could you maybe try again by inserting the one from the plugin? I actually also didn't know that there was a core block added which is called `row`. Maybe we need to change the name of our block in the future to avoid this confusion.

**Comment by tschortsch** [comment]
To solve your problem you can define a custom columns template for the row block which fits your needs with the [wpBootstrapBlocks.row.templates](https://github.com/liip/bootstrap-blocks-wordpress-plugin#wpbootstrapblocksrowtemplates) JavaScript filter. Afterwards you can override the default template of the row block with the [wp_bootstrap_blocks_row_default_attributes](https://github.com/liip/bootstrap-blocks-wordpress-plugin#wp_bootstrap_blocks_row_default_attributes) PHP filter. Tell me if you need help with this.

**Comment by rospencers** [comment]
@tschortsch Marvelous. Thanks very much for the tip, and the kind offer to assist! If I get bogged down, I'll reach out separately.

Meanwhile, since this particular "bug" is resolved (as operator error), I'll close this. Thanks again!
