### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by Sishasong** [liip/bootstrap-blocks-wordpress-plugin#112]
Hi there,

i'm trying to install node dependencies to update my PR for the accordion feature i got an ERESOLVE error with prettier package. 

`npm ERR! code ERESOLVE`
`npm ERR! ERESOLVE unable to resolve dependency tree`
`npm ERR!`
`npm ERR! While resolving: wp-bootstrap-blocks@4.2.1`
`npm ERR! Found: prettier@2.2.1-beta-1`
`npm ERR! node_modules/prettier`
`npm ERR!   dev prettier@"npm:wp-prettier@2.2.1-beta-1" from the root project`
`npm ERR!`
`npm ERR! Could not resolve dependency:`
`npm ERR! peer prettier@">=2.0.0" from eslint-plugin-prettier@4.2.1`
`npm ERR! node_modules/eslint-plugin-prettier`
`npm ERR!   dev eslint-plugin-prettier@"^4.0.0" from the root project`
`npm ERR!`
`npm ERR! Fix the upstream dependency conflict, or retry`
`npm ERR! this command with --force, or --legacy-peer-deps`
`npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`
`npm ERR!`
`npm ERR! See /root/.npm/eresolve-report.txt for a full report.`

After some research, i found this issues in gutenberg project https://github.com/WordPress/gutenberg/issues/39208 that seems to be the same things. 

After digging into wordpress-script, this package seems to be use only in format script which is not used in your project. IMO this dependency should be removed.

Best regards,
Célian

**Comment by tschortsch** [comment]
You're right, I just pushed the updated npm dependencies to the master branch. `npm install` should now work again.
