### ISSUE TITLE
How to add a class just to the row class, not the wp bootstrap blocks row class 

### ISSUE THREAD

**Issue by Jonofat** [liip/bootstrap-blocks-wordpress-plugin#12]
When I create a row, there are 2 divs created, one with wp bootstrap blocks row and then underneath that the normal boostrap row.

How can I add a class to the normal `<div class="row"></div>`? 

I tried adding a class through the options in Gutenberg but it adds the class to wp bootstrap blocks instead of just row.

I want it to look like `<div class="row justify-content-between"></div>`

**Comment by tschortsch** [comment]
Hi @Jonofat 

You can use the [`wp_bootstrap_blocks_row_classes`](https://github.com/liip/bootstrap-blocks-wordpress-plugin#wp_bootstrap_blocks_blockname_classes) filter for that:

```php
add_filter( 'wp_bootstrap_blocks_row_classes', 'my_custom_row_classes', 10, 2 );

function my_custom_row_classes( $classes, $attributes ) {
    array_push( $classes, 'justify-content-between' );
    return $classes;
}
```

**Comment by Jonofat** [comment]
Thank you, I will give that a try for sure!
