### ISSUE TITLE
Wrong Example in Documentation

### ISSUE THREAD

**Issue by unsalkorkmaz** [liip/bootstrap-blocks-wordpress-plugin#13]
Hi,

Thanks for plugin!

If I am not wrong;
`add_filter( 'wp_bootstrap_blocks_template_path', 'block-templates/' );`
should be
```
add_filter( 'wp_bootstrap_blocks_template_path', function(){ 
	return  'block-templates/';
});
```

**Comment by tschortsch** [comment]
You're totally right. It's fixed now!
