### ISSUE TITLE
Javascript-Filter seems not to work?!

### ISSUE THREAD

**Issue by nicmare** [liip/bootstrap-blocks-wordpress-plugin#23]
What is wrong? Do i need to modify something in your sample code? Expecting the new "Brand" Color would appear. But can't see it:
<img width="1237" alt="Screenshot 2019-11-05 15 58 32" src="https://user-images.githubusercontent.com/898582/68218917-66467d00-ffe5-11e9-978b-0a9b17a5ccf3.png">

**Comment by nicmare** [comment]
and how to get rid of that console warning with old object template structure?! this filter does not work either.

**Comment by tschortsch** [comment]
Hi @nicmare. These filter examples should work out of the box. You don't need to modify something. Is there an error in the browser console? Maybe your `editor.js` has an error above? If no could you maybe add the full `editor.js` source code and the way you are enqueuing this file? (Maybe there are some dependencies missing?)

The old object template structure can be disabled by returning `false` in the `wpBootstrapBlocks.row.useOldObjectTemplateStructure` filter https://github.com/liip/bootstrap-blocks-wordpress-plugin#wpbootstrapblocksrowuseoldobjecttemplatestructure. We will change this to be the default in a future version of this plugin.

**Comment by nicmare** [comment]
i already have some rules in my js file for gutenberg. they work. but your filters not:
`// styles for gutenberg:
function site_block_editor_styles() {
    wp_enqueue_style( 'gutenberg-styles', get_theme_file_uri( 'editor.css' ), false, '1.0', 'all' );
    wp_enqueue_script( 'be-editor', get_template_directory_uri() . '/assets/js/editor.js', array( 'wp-blocks', 'wp-dom' ), '1.0', true );
}
add_action( 'enqueue_block_editor_assets', 'site_block_editor_styles' );`
do i need to add something to the array?

**Comment by nicmare** [comment]
my js file get loaded after yours in source code:

<script type='text/javascript' src='http://localhost/wild/wp-content/plugins/wp-bootstrap-blocks/build/index.js?ver=1.3.1'></script>
--
  | <script type='text/javascript' src='http://localhost/wild/wp-content/themes/bootstrap/assets/js/editor.js?ver=1.0'></script>

**Comment by tschortsch** [comment]
Ahh I see. Your `editor.js` needs to be loaded before the plugins scripts. This is the only way the plugin can call the added filters. As a quick fix just add a higher priority than the default one (10) to your `enqueue_block_editor_assets` action like this:
`add_action( 'enqueue_block_editor_assets', 'site_block_editor_styles', 9 );`

We will set the blocks action priority to a higher value (> 10) in a future release of the plugin to avoid such problems.

**Comment by nicmare** [comment]
Nice! That works now! Sorry for that rookie mistake. But i am still new in Gutenberg Blocks… Thank you @tschortsch !

**Comment by tschortsch** [comment]
Glad that it works! I wouldn't call this a rookie mistake at all since this is not documented anywhere. We really need to adjust our action priority that the custom filters work with the default priority.
