### ISSUE TITLE
A UI method to add background colors to containers/columns

### ISSUE THREAD

**Issue by brianpurkiss** [liip/bootstrap-blocks-wordpress-plugin#3]
I know I can add classes to add backgrounds and text colors and other styles to blocks, but I can't tell a non-developer client to do that. 

Similarly, a single column layout would be neat to get paired with the background/text color. It would allow clients to add sections of content with alternating background colors. 

If we wanted to get super fancy, background images would be nifty, but I'd rather have a background and text color first.

**Comment by tschortsch** [comment]
Hi @brianpurkiss. We're implementing a background-color selector on a column level right now. It will probably included in the next version of the plugin.
You can already add your own row templates with the `wpBootstrapBlocks.row.templates` filter (see: https://github.com/liip/bootstrap-blocks-wordpress-plugin#wpbootstrapblocksrowtemplates).

I'm not sure if we will implement a background-image selector. This is probably what the Group Block in the upcoming Gutenberg 5.5 release (https://wptavern.com/gutenberg-5-5-adds-new-group-block-for-nesting-child-blocks) will be for.

**Comment by tschortsch** [comment]
We released version [1.1.0](https://github.com/liip/bootstrap-blocks-wordpress-plugin/releases/tag/1.1.0) of the plugin today. You can now set a background-color on the column block.
