### ISSUE TITLE
<div class="">

### ISSUE THREAD

**Issue by gettonet** [liip/bootstrap-blocks-wordpress-plugin#31]
Awesome tool! Thank you for sharing it.
Is it really necessary to have this wrapping div inside each column?
Whenever I make a column, all that's inside it gets a wrapping `<div class="">`
Is this a bug or it's on purpose?
Example:
`<div class="wp-bootstrap-blocks-row row py-5 mb-0">`
`<div class="col-12 col-md-6 align-self-center">`
`	<div class="">`
`		//////WHATEVER CONTENT INSIDE`
`        </div>`
`<div class="col-12 col-md-6 align-self-center">`
`	<div class="">`
`		//////WHATEVER CONTENT INSIDE`
`	</div>`
`</div>`
`</div>`

**Comment by gettonet** [comment]
Yeah, I found it in wp-bootstrap-blocks/src/templates/column.php....
Removed the inner div manually. 
While this might be good if it can be added optionally, I have found that if it's present always and by default, it's impossible to fully style inner content. For example, I have a group of blocks inside the column, and I give it a class "h-100" - but it's not doing anything because of the problematic wrapping div.
I suggest that you remove it, because in Gutenberg you have a group - so you can always set a group (wrapper) inside column and give it a class or id.

**Comment by tschortsch** [comment]
Hi @gettonet. Yes we're aware of this empty `<div>` in the column template. It is used to set the background-color if selected.
But you're right we could think about not rendering the div if there is no background-color chosen. In the meantime you can just create a new folder called `wp-boostrap-blocks/` inside of your theme folder and copy & paste the `wp-bootstrap-blocks/src/templates/column.php` template in this folder. You can then adjust it to your own needs without changing the plugin code (see: https://github.com/liip/bootstrap-blocks-wordpress-plugin#templates).

**Comment by tschortsch** [comment]
This is also fixed in version 2.1.0 of the plugin
