### ISSUE TITLE
How to Change Background Colors In PHP

### ISSUE THREAD

**Issue by gpsugy** [liip/bootstrap-blocks-wordpress-plugin#35]
The docs say that background colors for columns can be modified in JavaScript, labeled "wpBootstrapBlocks.column.bgColors." Is there a way to configure these options using PHP `add_filter`? If so, what is the syntax? A reference listing out all the PHP equivalents of the JavaScript ones would be also much appreciated.

Great plugin, by the way!

**Comment by tschortsch** [comment]
Hi @gpsugy. There is sadly no way to use the JavaScript filters in PHP. This is not possible since they modify the Gutenberg editor on the client side.

**Comment by gpsugy** [comment]
@tschortsch I see. Thanks for your reply. To utilize the JavaScript filters, I can follow the instructions at the following link, correct? https://github.com/liip/bootstrap-blocks-wordpress-plugin/issues/10

**Comment by tschortsch** [comment]
Yes exactly!
