### ISSUE TITLE
publish to gutenbergcloud.org

### ISSUE THREAD

**Issue by attisan** [liip/bootstrap-blocks-wordpress-plugin#40]
would be great to see this effort be published to [gutenbergcloud.org](https://gutenbergcloud.org) so WordPress and Drupal devs would have access to the bootstrap blocks with little to no effort?

**Comment by tschortsch** [comment]
Good idea! I will look into it.

**Comment by tschortsch** [comment]
I looked into gutenbergcloud.org and sadly it looks like we won't be able to publish this plugin there. The project only supports JS/CSS-only Gutenberg blocks. Our blocks are build as dynamic blocks (server side rendered) using PHP templates.
