### ISSUE TITLE
WP5.4, backend layout issues

### ISSUE THREAD

**Issue by gettonet** [liip/bootstrap-blocks-wordpress-plugin#42]
Looks like Gutenberg changed its css, so columns are overlapping. I kinda quick solved it by adding a 14px padding to the block, but it obviously needs to be fixed in an update.

`.wp-block-wp-bootstrap-blocks-row > .block-editor-inner-blocks > .block-editor-block-list__layout > [data-type="wp-bootstrap-blocks/column"], .wp-block-wp-bootstrap-blocks-row > .editor-inner-blocks > .editor-block-list__layout > [data-type="wp-bootstrap-blocks/column"] {
    padding: 14px;
}`

**Comment by tschortsch** [comment]
You're right. I will try to fix this issue. Our main problem when changing the styling of our blocks is to keep backwards compatibility with older versions of WordPress (and Gutenberg). But let's see what we can do.

**Comment by tschortsch** [comment]
Should be fixed in version `2.1.0` (see: https://github.com/liip/bootstrap-blocks-wordpress-plugin/releases/tag/2.1.0)
