### ISSUE TITLE
All blocks are gone.

### ISSUE THREAD

**Issue by npmDude** [liip/bootstrap-blocks-wordpress-plugin#53]
After updating to version v2.4.0 and also updating Gutenberg to v8.5.1, all of the bootstrap blocks are gone.
This time no error on the console.

Note: I also have a plugin that uses the wp-scripts' latest version.

Please try to test this on your end.

**Comment by tschortsch** [comment]
Hmm, sorry I can't really reproduce this. I tried it with the following setup:
- WordPress v5.4.2
- wp-bootstrap-blocks v2.4.0 (which uses @wordpress/scripts v12.1.0)
- wp-scripts-plugin (example plugin which also uses @wordpress/scripts v12.1.0)
- Gutenberg v8.5.1

When I activate all of these plugins I'm still able to insert the blocks provided by them.

**Comment by npmDude** [comment]
Is this working on npm run build also?

**Comment by tschortsch** [comment]
Yes, both plugins use assets which were built with the `npm run build` command.

**Comment by npmDude** [comment]
Can you try adding 2 blocks on your wp-scripts-plugin? Maybe a copy of the Row and Column block from the wp-bootstrap-blocks. Just because when I added a blocks on my plugin that has a parent and allowed blocks relation, then all of the blocks from wp-bootstrap-blocks plugin is gone. Without any errors on the console.

**Comment by tschortsch** [comment]
I copy/pasted both the `row` and `column` blocks (including parent/child relation) from this plugin to the `wp-scripts-plugin` and the blocks were still all available.

**Comment by npmDude** [comment]
Alright thanks. Maybe this is an internal problem. It is really hard because there is on console error.

**Comment by npmDude** [comment]
After a few more testing, I noticed that on my plugin if I rearrange the import on the src/index.js file then blocks from your plugin will comeback. Do you have any idea on why this is happening?

**Comment by tschortsch** [comment]
Maybe there's still an issue in the @wordpress/scripts package? Is your plugin somewhere on GitHub or could you share the it?
