### ISSUE TITLE
Strange className encoding

### ISSUE THREAD

**Issue by forcecodema** [liip/bootstrap-blocks-wordpress-plugin#61]
Hi,

Double minus sign in className property is encoded in the following way:

```
<!-- wp:wp-bootstrap-blocks/column {"className":"offer-deep\u002d\u002dimg_wrapper"} -->
```

className entered in editor is `offer-deep--img_wrapper`

Regards,

Michal

**Comment by tschortsch** [comment]
Hmm we're actually using the official className attribute of Gutenberg. But I will look into that.

**Comment by tschortsch** [comment]
This looks like the default behavior of the editor. It also happens with core blocks. I tried it with the `core/paragraph` block:
```
<!-- wp:paragraph {"className":"test\u002d\u002dclass test-class"} -->
```
It seems that a double dash gets encoded with unicode characters when saved in the className attribute. But the output on the page seems to be correct again:
```
<p class="test--class test-class">
```

**Comment by openmindculture** [comment]
So this encoding is not mandatory to keep when persisting the code in a block pattern file.
