### ISSUE TITLE
Wouldn't be great to support stretch vertical alignment to row > column ? 

### ISSUE THREAD

**Issue by Wewill** [liip/bootstrap-blocks-wordpress-plugin#75]
Hi team, 

Actually, it's possible to verticaly align column in a row : start, center, end. Which is great if you don't have a background color in column. In this case, wouldn't be great to support stretch alignment to fit equal heights to each columns ? 

verticalAlignment > adding stretch 

<img width="1663" alt="Capture d’écran 2021-05-13 à 10 01 36" src="https://user-images.githubusercontent.com/3178443/118096922-4f4ecb00-b3d2-11eb-9b9e-bf776eb61a9d.png">
<img width="1663" alt="Capture d’écran 2021-05-13 à 10 01 48" src="https://user-images.githubusercontent.com/3178443/118096926-51188e80-b3d2-11eb-8e01-f97730943b46.png">

Best regards, Wilhem

**Comment by tschortsch** [comment]
Hi @Wewill. Currently it's possible to enable the `Center content vertically` (see: https://github.com/liip/bootstrap-blocks-wordpress-plugin#options-2) checkbox in the column options. This sets a height of 100% to the column and centers its content vertically. But you're right, it is not possible to do the same if the content should be aligned to the top.

**Comment by Wewill** [comment]
Hi @tschortsch, 

Thanks a lot for your quick reply ; yes it will be very useful. 
And may I suggest to add this parameter to the column toolbar or in a group in metaboxes ? After padding group > `Inner column alignement` or something relevant. 

Your plugin is perfect, simple, clean and useful ! Thanks a lot. 

Best regards, Wilhem

**Comment by tschortsch** [comment]
Good idea. Since this setting is related to the background setting we wanted to keep those together. But we will think about this if we implement further options for it.

**Comment by tschortsch** [comment]
Hi @Wewill. We just released `v3.3.0` of the plugin which supports to vertical align the content of a column block via the block toolbar. The setting is still on column-level (and not on the row block) to not create a dependency (on template side) between those two blocks.
