### ISSUE TITLE
Several stylesheet files loaded on front-end

### ISSUE THREAD

**Issue by briansteeleca** [liip/bootstrap-blocks-wordpress-plugin#8]
I see that there's several stylesheets being loaded on the front-end – I'm wondering if these are necessary for the front-end or if some should only be loaded in the admin dashboard?

- /wp-content/plugins/bootstrap-blocks-wordpress/dist/blocks.style.build.css?ver=1.1.0
- /wp-includes/css/dist/editor/style.min.css?ver=5.2.2
- /wp-includes/css/dist/nux/style.min.css?ver=5.2.2
- /wp-includes/css/dist/block-editor/style.min.css?ver=5.2.2
- /wp-includes/css/dist/components/style.min.css?ver=5.2.2
- https://fonts.googleapis.com/css?family=Noto+Serif%3A400%2C400i%2C700%2C700i&ver=5.2.2

It looks like a fantastic plugin, but I'd like to see less requests for CSS files.

**Comment by tschortsch** [comment]
Thanks for the bug report! You're right, there was a dependency to the `wp-editor` styles while loading our own block styles which we didn't really need.
We just released a new version of the plugin [`1.2.0`](https://github.com/liip/bootstrap-blocks-wordpress-plugin/releases/tag/1.2.0) which removes this dependency. It also comes with a new filter `wp_bootstrap_blocks_enqueue_block_assets` which makes it possible to disable enqueuing the plugin stylesheet itself.

**Comment by briansteeleca** [comment]
Thanks for fixing this so quickly @tschortsch, this is perfect! And I must say, I love user experience of this plugin in the editor – so easy to use. I'm looking forward to using it in the real world. Thanks for your great work! :)
