### ISSUE TITLE
Filter to disable button

### ISSUE THREAD

**Issue by huubl** [liip/bootstrap-blocks-wordpress-plugin#80]
Hi,

I only want to use the container/row/column blocks. What do you think about a filter to disable the button block?

**Comment by tschortsch** [comment]
Hi @huubl. You should be able to use the WordPress core `unregisterBlockType` filter to achieve this. See https://developer.wordpress.org/block-editor/reference-guides/filters/block-filters/#using-a-deny-list for the documentation.

**Comment by huubl** [comment]
Thanks! got it working:

```
import { unregisterBlockType } from '@wordpress/blocks';
import domReady from '@wordpress/dom-ready';
 
domReady( function () {
    unregisterBlockType('wp-bootstrap-blocks/button');
} );
```
